jenkins-x-platform:
  PipelineSecrets:
    DockerConfig: |-
      {
        "credsStore": "acr-linux"
      }
  docker-registry:
    enabled: false
  nexus:
    enabled: false
  postinstalljob:
    enabled: "true"
